# Generated by Django 5.0.6 on 2024-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('grande', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha subida')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ancho')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='alto')),
                ('blurBase64', models.CharField(blank=True, max_length=800, null=True, verbose_name='blur')),
            ],
        ),
    ]
