# Generated by Django 4.2.13 on 2024-06-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('grande', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha subida')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ancho')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='alto')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='descripcion')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='nombre')),
                ('blurBase64', models.CharField(blank=True, max_length=800, null=True, verbose_name='blur')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Miniatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('grande', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha subida')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ancho')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='alto')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='descripcion')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='nombre')),
                ('blurBase64', models.CharField(blank=True, max_length=800, null=True, verbose_name='blur')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='descripcion')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='nombre')),
                ('miniatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.miniatura')),
            ],
        ),
    ]
