# Generated by Django 5.0.6 on 2024-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descripcion'),
        ),
    ]
