# Generated by Django 4.2.13 on 2024-06-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='descripcion')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='nombre'),
        ),
    ]
