# Generated by Django 5.0.6 on 2024-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_imagen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.CharField(default='', max_length=300, verbose_name='descripcion'),
        ),
    ]
