# Generated by Django 4.2.13 on 2024-06-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_imagen_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='descripcion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['-id'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
    ]
